In [1]:
import pandas as pd
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [2]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [3]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [5]:
#Inner Join (default)
pd.merge(employees,departments,on="DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [6]:
#Left Join
pd.merge(employees, departments, on="DeptID", how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [7]:
#Right Join
pd.merge(employees, departments, on="DeptID", how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [8]:
#Outer Join
pd.merge(employees, departments, on="DeptID", how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [9]:
#Concatenating DataFrames
#Vertical (rows)
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [11]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"],"Score":[443,221]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"],"age":[33,44]})

pd.concat([df1, df2])

      Name  Score   age
0    Alice  443.0   NaN
1      Bob  221.0   NaN
0  Charlie    NaN  33.0
1    David    NaN  44.0

In [12]:
#Horizontal (columns)
df1 = pd.DataFrame({"ID": [1, 2]})
df2 = pd.DataFrame({"Score": [90, 80]})

pd.concat([df1, df2], axis=1)

   ID  Score
0   1     90
1   2     80